# Generated by Django 2.2.5 on 2019-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatlog',
            name='eat_datetime',
            field=models.DateField(),
        ),
    ]
