# Generated by Django 2.2.5 on 2019-12-03 01:56

from django.db import migrations, models
import menu_proposal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_name', models.TextField(verbose_name='アレルギー名')),
            ],
            options={
                'verbose_name': 'allergies',
                'verbose_name_plural': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.TextField(verbose_name='ジャンル名')),
            ],
            options={
                'verbose_name': 'Genres',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=128, unique=True, verbose_name='名前')),
                ('menu_value', models.IntegerField(verbose_name='価格')),
                ('menu_energy', models.FloatField(verbose_name='カロリー')),
                ('menu_carbohydrate', models.FloatField(verbose_name='炭水化物')),
                ('menu_salt_content', models.FloatField(verbose_name='塩分')),
                ('menu_lipid', models.FloatField(verbose_name='脂質')),
                ('menu_protein', models.FloatField(verbose_name='タンパク質')),
                ('menu_red_point', models.FloatField(verbose_name='赤')),
                ('menu_green_point', models.FloatField(verbose_name='緑')),
                ('menu_yellow_point', models.FloatField(verbose_name='黄')),
                ('menu_picture', models.ImageField(blank=True, null=True, upload_to=menu_proposal.models.get_file_path, verbose_name='画像')),
                ('menu_allergies', models.ManyToManyField(blank=True, null=True, to='menu_proposal.Allergies', verbose_name='アレルギー')),
                ('menu_genre', models.ManyToManyField(to='menu_proposal.Genres', verbose_name='ジャンル')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
    ]
